### ISSUE TITLE
Download not working again

### ISSUE THREAD

**Issue by etendards** [prolane/samltoawsstskeys#25]
We have Okta MFA disabled currently in our dev environment.  And now I am not getting the credentials download again.  Is anyone else experiencing issues?  I even tried incognito so not many extensions are loaded.

Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by BrandonDusseau** [comment]
I'm experiencing the same issue now. Any updates?

**Comment by prolane** [comment]
Still working with ADFS.

Could you guys share the error logs.
Go to Extensions, turn on 'Developer Mode', and then click 'Inspect views background/background.html' for this extension. This will give you a new window with the console open. Try to use the extension and please share whatever output is generated.

**Comment by BrandonDusseau** [comment]
POST https://sts.amazonaws.com/ 400 (Bad Request)
    script.js:152 Error: The requested DurationSeconds exceeds the MaxSessionDuration set for this role.
        at constructor.s (aws-sdk-2.7.5.min.js:35)
        at constructor.callListeners (aws-sdk-2.7.5.min.js:36)
        at constructor.emit (aws-sdk-2.7.5.min.js:36)
        at constructor.emitEvent (aws-sdk-2.7.5.min.js:35)
        at constructor.e (aws-sdk-2.7.5.min.js:35)
        at a.runTo (aws-sdk-2.7.5.min.js:37)
        at aws-sdk-2.7.5.min.js:37
        at constructor.<anonymous> (aws-sdk-2.7.5.min.js:35)
        at constructor.<anonymous> (aws-sdk-2.7.5.min.js:35)
        at constructor.callListeners (aws-sdk-2.7.5.min.js:36) "ValidationError: The requested DurationSeconds exceeds the MaxSessionDuration set for this role.
        at constructor.s (chrome-extension://ekniobabpcnfjgfbphhcolcinmnbehde/lib/aws-sdk-2.7.5.min.js:35:9093)
        at constructor.callListeners (chrome-extension://ekniobabpcnfjgfbphhcolcinmnbehde/lib/aws-sdk-2.7.5.min.js:36:2887)
        at constructor.emit (chrome-extension://ekniobabpcnfjgfbphhcolcinmnbehde/lib/aws-sdk-2.7.5.min.js:36:2596)
        at constructor.emitEvent (chrome-extension://ekniobabpcnfjgfbphhcolcinmnbehde/lib/aws-sdk-2.7.5.min.js:35:22039)
        at constructor.e (chrome-extension://ekniobabpcnfjgfbphhcolcinmnbehde/lib/aws-sdk-2.7.5.min.js:35:17889)
        at a.runTo (chrome-extension://ekniobabpcnfjgfbphhcolcinmnbehde/lib/aws-sdk-2.7.5.min.js:37:8555)
        at chrome-extension://ekniobabpcnfjgfbphhcolcinmnbehde/lib/aws-sdk-2.7.5.min.js:37:8762
        at constructor.<anonymous> (chrome-extension://ekniobabpcnfjgfbphhcolcinmnbehde/lib/aws-sdk-2.7.5.min.js:35:18099)
        at constructor.<anonymous> (chrome-extension://ekniobabpcnfjgfbphhcolcinmnbehde/lib/aws-sdk-2.7.5.min.js:35:22094)
        at constructor.callListeners (chrome-extension://ekniobabpcnfjgfbphhcolcinmnbehde/lib/aws-sdk-2.7.5.min.js:36:2993)"

**Comment by BrandonDusseau** [comment]
It looks like the extension works for one role but fails for two others in my organization.

**Comment by prolane** [comment]
Please see this closed issue:
https://github.com/prolane/samltoawsstskeys/issues/17

Its about `Error: The requested DurationSeconds exceeds the MaxSessionDuration set for this role.`

This means you are requesting access for a longer duration than what is allowed for this IAM role.

**Comment by prolane** [comment]
From the 2.3 release notes:

> Release 2.2 revealed many users have their SAML provider requesting a SessionDuration which is higher than the maximum session duration configured at the IAM Role. Release 2.3 now supports manually enabling or disabling this SessionDuration feature. The feature is enabled by default, but can be disabled in the options.

**Comment by BrandonDusseau** [comment]
Thanks! I didn't see that before. It's working for me now that I've disabled the option.
However, I do feel bad for hijacking the original reporter's issue in case they are not having the same problem as me.

**Comment by prolane** [comment]
Great! I'll add this bit to the readme soon as I guess its a common question.

I'll let the issue open for a few days so @etendards has a chance to respond as well.

**Comment by etendards** [comment]
Interesting.  Mine is now working too.  I am not sure anything changed on
my system.  I think I rebooted Widows the other day.

**Comment by prolane** [comment]
I'm confused @etendards . You mentioned its working. So when does the error popup? Could you please paste the complete stack trace from the console?

403 Forbidden would suggest your user does not have permissions for doing the STS action 'AssumeRoleWithSAML'.
https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awssecuritytokenservice.html#awssecuritytokenservice-actions-as-permissions
